### PR TITLE
auto cast std::string to c_str for lua values

### PR DESCRIPTION
**Pull request by fritzy**
See issue #10

### CODE REVIEW

**Comment by fritzy** [comment]
Hey, how about that, the Travis CI builds pass now. Sorry about that!

**Comment by AdUki** [comment]
No problem, it was Lua 5.2 API. The call _lua_objlen_ has different name 
there...

**Comment by fritzy** [comment]
I think you're referring to my other pull request with lua_objlen. This one is for string auto-casting. Sorry about the issue on the other one though! :)

**Comment by AdUki** [comment]
Ah, yes. It was other issue. Thx for contributing

**Pull request merged**
